name = "DBInterface"
uuid = "a10d1c49-ce27-4219-8d33-6db1a4562965"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "2.4.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
